language: node_js
node_js:
  - stable

before_install:
# DONT SETUP GH_TOKEN here, set it in Travis to avoid the security issue
# git setup
  - git config --global push.default matching
  - git config --global user.name "hihihippp"
  - git config --global user.email "liuzhangang@gmail.com"
# github user name
  - export ACCOUNT=hihihippp
# github project name
  - export REPO=ghpage-auto-deploy
# the folder that will be upload to gh-page
  - export FOLDER_TO_UPLOAD=build
# target export branch
  - export BRANCH=gh-pages
# check /usr/share/zoneinfo/ for valid timezone
# used in auto commit message
  - export TIMEZONE=Asia/Shanghai

install:
  - npm install

script:
# your build process
  - rm -Rf build
  - mkdir build
  - cp index.html build/
  - cp -r js build/
  - cp -r css build/
  - cp -r asciinema-cast build/
# deploy via travis
# check details on https://github.com/gasolin/ghpage-auto-deploy
  - ./deploy.sh

branches:
  only:
# the source branch
    - master

cache:
  directories:
    - node_modules
